[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.columns = 150
dimensions.lines = 50
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14
